name: Setup cibuildwheel caching
description: 'Setup cibuildwheel caching'

inputs:
  version:
    type: choice
    description: 'Python Version to use'
    options:
      - '3.9'
      - '3.10'
      - '3.11'
      - '3.12'
    default: '3.9'

runs:
  using: 'composite'
  steps:
    - name: Install platformdirs
      run: pip install -U platformdirs
      shell: bash

    - name: Display cibuildwheel cache dir
      id: cibuildwheel-cache
      run: |
        from platformdirs import user_cache_path
        import os

        with open(os.getenv('GITHUB_OUTPUT'), 'w') as f:
          f.write(f"dir={str(user_cache_path(appname='cibuildwheel', appauthor='pypa'))}")
      shell: python

    - name: Cache cibuildwheel tools
      uses: actions/cache@v3
      with:
        path: ${{ steps.cibuildwheel-cache.outputs.dir }}
        key: ${{ runner.os }}-cibuildwheel-${{ inputs.version }}
