version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/download-dist"
      - "/run-cibuildwheel"
      - "/setup"
      - "/setup-cibuildwheel"
      - "/setup-cibuildwheel-cache"
      - "/test-sdist"
      - "/test-wheel"
      - "/upload-dist"
    schedule:
      interval: "monthly"
    labels: []
