name: Setup Python
description: 'Ensure python is installed, and setup pypi caching'

inputs:
  version:
    type: choice
    description: "Version to install"
    options:
      - '3.9'
      - '3.10'
      - '3.11'
      - '3.12'
    default: '3.11'

runs:
  using: 'composite'
  steps:
    - name: Set up Python ${{ inputs.version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.version }}
        cache: "pip"
        cache-dependency-path: |
          "**/pyproject.toml"
          "**/setup.py"

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        ignore-nothing-to-cache: true
        prune-cache: false

    - name: Setup uv to use system python without extra flags
      shell: bash
      run: echo "UV_SYSTEM_PYTHON=1" >> $GITHUB_ENV
