name: Setup Python
description: 'Ensure python is installed, and setup pypi caching'

inputs:
  version:
    type: choice
    description: "Version to install"
    options:
      - '3.7'
      - '3.8'
      - '3.9'
      - '3.10'
      - '3.11'
    default: '3.9'

runs:
  using: 'composite'
  steps:
    - name: Setup Pip caching
      uses: actions-ext/python/setup-cache@v1

    - name: Set up Python ${{ inputs.version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.version }}
        cache: "pip"
        cache-dependency-path: |
          "**/pyproject.toml"
          "**/setup.py"
