name: Setup Python
description: 'Ensure python is installed, and setup pypi caching'

inputs:
  version:
    type: choice
    description: "Version to install"
    options:
      - '3.9'
      - '3.10'
      - '3.11'
      - '3.12'
      - '3.13'
      - '3.13t'
      - '3.14'
      - '3.14t'
    default: '3.11'
  uv:
    type: boolean
    description: "Use uv to install python packages"
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Set up Python ${{ inputs.version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.version }}
        allow-prereleases: true
      if: ${{ inputs.uv == 'true' }}

    - name: Set up Python ${{ inputs.version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.version }}
        allow-prereleases: true
        cache: "pip"
        cache-dependency-path: |
          "**/pyproject.toml"
          "**/setup.py"
      if: ${{ inputs.uv != 'true' }}

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: "${{ inputs.version }}"
        enable-cache: true
        ignore-nothing-to-cache: true
        prune-cache: false
      if: ${{ inputs.uv == 'true' }}

    - name: Setup uv to use system python without extra flags
      shell: bash
      run: echo "UV_SYSTEM_PYTHON=1" >> $GITHUB_ENV
      if: ${{ inputs.uv == 'true' }}

    - name: Install uv as a python package for use of `python -m uv`
      shell: bash
      run: |
        uv pip install pip
        python -m pip install uv
      if: ${{ inputs.uv == 'true' }}
